language: python
python:
  - 3.8.5
services:
  - postgresql
before_install:
  - openssl aes-256-cbc -K $encrypted_7c1e5bdef461_key -iv $encrypted_7c1e5bdef461_iv
    -in app-engine.json.enc -out app-engine.json -d
  - cd backend
install:
  - pip install -r requirements.txt
before_script:
  - psql -U postgres -c "CREATE USER test with PASSWORD 'test';"
  - psql -U postgres -c "ALTER USER test CREATEDB;"
  - psql -U postgres -c "CREATE DATABASE test;"
  - python manage.py collectstatic --no-input --clear
script:
  - python manage.py migrate --noinput
  - python manage.py test
  - ./process-env.sh
deploy:
  provider: gae
  keyfile: "../app-engine.json"
  config: "./app.yaml"
  project: portfolify
  default: true
  skip_cleanup: true
