version: "3.8"

services:
  ## entry point for portfolify app containers
  app-reverse-proxy:
    image: jermytan/portfolify-reverse-proxy
    build:
      context: ./app-reverse-proxy
    volumes:
      - static-volume:/app/static
    networks:
      - frontend
      - backend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  ## can only be accessed from same network
  frontend:
    image: jermytan/portfolify-frontend
    build:
      context: ./frontend
    networks:
      - frontend
    restart: always

  ## can only be accessed from same network
  backend:
    image: jermytan/portfolify-backend
    build:
      context: ./backend
    command: gunicorn portfolify.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static-volume:/app/static
    networks:
      - backend
    restart: always
    env_file:
      - ./backend/.env.backend.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.db.dev
    restart: always

networks:
  frontend:
  backend:

volumes:
  postgres-data:
  static-volume:
