version: "3.8"

services:
  ## entry point for portfolify app containers
  app-reverse-proxy:
    image: jermytan/portfolify-reverse-proxy
    build:
      context: ./app-reverse-proxy
    networks:
      - frontend
      - backend
    restart: always
    ports:
      - "80:80"

  ## can only be accessed from same network
  frontend:
    image: jermytan/portfolify-frontend
    build:
      context: ./frontend
    networks:
      - frontend
    restart: always

  ## can only be accessed from same network
  backend:
    image: jermytan/portfolify-backend
    build:
      context: ./backend
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:
