version: "3.8"

services:
  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.backend.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env.db.dev
    restart: always

volumes:
  postgres-data:
