# Generated by Django 3.1 on 2020-08-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('image_URL', models.URLField(blank=True, null=True)),
                ('delete_image_URL', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
