# Generated by Django 3.1 on 2020-08-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200830_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='delete_image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default=3424242, max_length=50),
            preserve_default=False,
        ),
    ]
