# Generated by Django 3.1 on 2020-09-01 11:21

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200830_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
